name: Bandit SAST Scan

on:
  pull_request: # Runs on pull requests
  push:
    branches:
      - main # Adjust this branch to your default branch as needed
      - feature/test-push-2

jobs:
  bandit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install Bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run Bandit SAST Scan
        run: bandit -r . --exit-zero -ll -f json -o bandit_file.json -x "tests/*,test/*,*/tests/*,*/test/*,venv/*,*/venv/*,scripts/*,*/scripts/*,temp/*,*/temp/*"

  triageAndRemediation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout submit-run-action
        uses: actions/checkout@v4
        with:
          repository: AppSecureAI/submit-run-action
          token: ${{ secrets.ACTION_PAT }}
          path: .github/actions/submit-run-action
          ref: main

      - name: Run AppSecAI
        uses: ./.github/actions/submit-run-action
        with:
          file: bandit_file.json
